-- Database and Schema Setup


-- 1. Create and select the database
DROP DATABASE IF EXISTS pressstart_db;
CREATE DATABASE pressstart_db;
USE pressstart_db;

-- 2. Create Games Table
CREATE TABLE games (
    game_id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    genre VARCHAR(50),
    release_year INT,
    price_per_day DECIMAL(4,2),
    stock_count INT
);

-- 3. Create Members Table
CREATE TABLE members (
    member_id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    membership_type VARCHAR(20) DEFAULT 'Standard',
    join_date DATE
);

-- 4. Create Rentals Table
CREATE TABLE rentals (
    rental_id INT AUTO_INCREMENT PRIMARY KEY,
    member_id INT,
    game_id INT,
    rental_date DATE,
    days_rented INT,
    return_status VARCHAR(20), -- 'Returned' or 'Overdue'
    FOREIGN KEY (member_id) REFERENCES members(member_id),
    FOREIGN KEY (game_id) REFERENCES games(game_id)
);


-- Sample Data Insertion

-- Insert Sample Games
INSERT INTO games (title, genre, release_year, price_per_day, stock_count) VALUES
('Super Mario Odyssey', 'Platformer', 2017, 2.50, 5),
('The Legend of Zelda: Skyward Sword', 'Adventure', 2011, 1.99, 3),
('Mario Kart 8 Deluxe', 'Racing', 2017, 2.50, 0),
('Elden Ring', 'RPG', 2022, 3.99, 4),
('Cyberpunk 2077', 'RPG', 2020, 2.99, 2),
('Sonic Frontiers', 'Platformer', 2022, 1.99, 3);

-- Insert Sample Members
INSERT INTO members (username, membership_type, join_date) VALUES
('PixelKnight', 'Premium', '2025-01-10'),
('RetroQueen', 'Standard', '2025-03-14'),
('GlitchMaster', 'Premium', '2025-04-02'),
('ControllerChaos', 'Standard', '2025-11-20'),
('Speedrunner99', 'VIP', '2026-01-05');

-- Insert Sample Rentals
INSERT INTO rentals (member_id, game_id, rental_date, days_rented, return_status) VALUES
(1, 1, '2026-04-10', 3, 'Returned'),
(2, 2, '2026-04-12', 5, 'Returned'),
(3, 4, '2026-04-15', 7, 'Overdue'),
(1, 3, '2026-04-18', 2, 'Returned'),
(4, 5, '2026-04-20', 4, 'Returned'),
(5, 4, '2026-04-22', 10, 'Overdue'),
(2, 1, '2026-04-25', 3, 'Returned'),
(3, 6, '2026-04-26', 2, 'Returned'),
(1, 5, '2026-04-28', 5, 'Returned'),
(5, 2, '2026-04-29', 4, 'Returned');


-- 10 New Practice Queries
-- 1.Find all games that have "Mario" anywhere in their title.

SELECT title, genre, release_year 
FROM games 
WHERE title LIKE '%Mario%';

-- 2.Find the top 3 most expensive games to rent per day.
SELECT title, price_per_day 
FROM games 
ORDER BY price_per_day DESC 
LIMIT 3;

-- 3.Find all games where the stock is completely empty.
SELECT title, genre 
FROM games 
WHERE stock_count = 0;

-- 4.Classify games into "Retro" or "Modern" based on their release year.

SELECT title, release_year,
       CASE 
           WHEN release_year < 2020 THEN 'Retro/Classic'
           ELSE 'Modern Era'
       END AS game_category
FROM games;

-- 5.Group rentals by game and show only the games that have been rented more than once. (Note: WHERE filters rows before grouping; HAVING filters after grouping!)

SELECT game_id, COUNT(rental_id) AS rental_count
FROM rentals
GROUP BY game_id
HAVING rental_count > 1;

-- 6.Find the average rental duration (days rented) for each unique return status.
SELECT return_status, AVG(days_rented) AS avg_days_kept
FROM rentals
GROUP BY return_status;

-- 7.Count how many unique games have actually been rented out at least once.
SELECT COUNT(DISTINCT game_id) AS unique_games_rented 
FROM rentals;

-- 8.Find usernames of members who currently hold an "Overdue" game rental.

SELECT username, membership_type 
FROM members 
WHERE member_id IN (SELECT member_id FROM rentals WHERE return_status = 'Overdue');

-- 9.Display a history list showing the game titles alongside the dates they were checked out.
SELECT r.rental_date, g.title, r.return_status
FROM rentals r
INNER JOIN games g ON r.game_id = g.game_id
ORDER BY r.rental_date DESC;

-- 10.Calculate the total money generated by each member by multiplying their days_rented by the game's price_per_day
SELECT m.username, 
       SUM(r.days_rented * g.price_per_day) AS total_spent
FROM rentals r
INNER JOIN members m ON r.member_id = m.member_id
INNER JOIN games g ON r.game_id = g.game_id
GROUP BY m.username
ORDER BY total_spent DESC;
